### ISSUE TITLE
License confusion between pyproject.toml and LICENSE file

### ISSUE THREAD

**Issue by hyandell** [python-postgres/fe#127]
Recognizing that you encourage other projects to generally be used, I wanted to report a clarification on the licensing of the project that appears to have been lost over the years.

The pyproject.toml lists four licenses applying to the project - BSD, MIT, PSF, and the fairly obscure AAL. The LICENSE file itself lists BSD-3-Clause. Digging back through the various versions of project metadata, I saw that this was introduced in the original GitHub version in 2009: https://github.com/python-postgres/fe/commit/b7c9dec5285996311c8dbc9f7a4a9711a0e8c169

The source headers from that time point to the following website, with license page (using archive.org): https://web.archive.org/web/20071102222458/http://python.projects.postgresql.org/license.html

I notice that the license at that time is described as BSD-3-Clause, but includes the following paragraph:

```
Substitute Terms
    
The primary license, being the above, is considered to be a gift license. Therefore, you are hereby granted the authorization to use any of the works created by the pg/python project under the terms and conditions of the MIT License, or the PSF License, or the Attribution Assurance license, or the Creative Commons Attribution 2.0 License, or the Fair License.
```

I assume that this is why the four licenses are listed in the package metadata, having (reasonably) dropped CC-BY-2.0 (not recommended for software by CC) and the obscure Fair license.

I'm sharing this here for others following the same path. For the project - one thought would be to add a statement back, perhaps to the README file. Another thought is to consider dropping the AAL license - I got interested in this after seeing AAL, which has some peculiar wording, and wondering what the history was.

**Comment by jwp** [comment]
Been a while since I read the AAL. My recollection is that all those licenses share intent.

Could you be specific about what your concern is? Is there a legal technicality that has severe implications in the Lithuanian courts?

**Comment by jwp** [comment]
Yes, it's an OR list. And, thank you for noting this as there is/was no intention to require people using this library to display a copyright notice every time their program is ran. It also seems suspicious to be enforceable without greater clarity, on my part, of what the "program" is given py-postgresql being a library. If it were interpreted as any/all of it, it would certainly create some usability problems.

As to "this GPG-signed text". I'd guess that the author of the license intended users, me in this case, to digitally sign the license in order to provide some assurance of its authenticity.

I'm trying to recall why I included it, and I think it was just that it was no bother to include it. It was "open source" and "promoted attribution". Or maybe it was "Not sure why you'd choose this license over the others, but here it is if you want it". It is inconsistent enough with the others to potentially cause some confusion.

**Comment by jwp** [comment]
For clarity. The license list is intended to be a choice. The attribution notification requirements of the Attribution Assurance License do not apply if you choose to use another license.
